// VersoRefuerzo — Design Tokens
// Vibrante y juvenil con respeto reverente.
// Paleta: indigo/violet/azure principales, acentos cálidos para tarjetas.

const VR = {
  // brand gradients
  brand: {
    primary: 'linear-gradient(135deg, #6366F1 0%, #8B5CF6 50%, #A855F7 100%)',
    primarySoft: 'linear-gradient(135deg, #818CF8 0%, #A78BFA 100%)',
    sky: 'linear-gradient(135deg, #38BDF8 0%, #6366F1 100%)',
    sunrise: 'linear-gradient(135deg, #FBBF24 0%, #F472B6 50%, #A855F7 100%)',
    forest: 'linear-gradient(135deg, #34D399 0%, #14B8A6 100%)',
    ember: 'linear-gradient(135deg, #FB923C 0%, #EF4444 100%)',
    rose: 'linear-gradient(135deg, #F472B6 0%, #EC4899 100%)',
    night: 'linear-gradient(135deg, #1E1B4B 0%, #312E81 50%, #4C1D95 100%)',
  },
  // solid colors
  c: {
    indigo50: '#EEF2FF',
    indigo100: '#E0E7FF',
    indigo200: '#C7D2FE',
    indigo400: '#818CF8',
    indigo500: '#6366F1',
    indigo600: '#4F46E5',
    indigo700: '#4338CA',
    indigo900: '#312E81',
    indigo950: '#1E1B4B',
    violet400: '#A78BFA',
    violet500: '#8B5CF6',
    violet600: '#7C3AED',
    purple500: '#A855F7',
    pink500: '#EC4899',
    pink400: '#F472B6',
    amber400: '#FBBF24',
    amber500: '#F59E0B',
    emerald400: '#34D399',
    emerald500: '#10B981',
    teal500: '#14B8A6',
    sky400: '#38BDF8',
    sky500: '#0EA5E9',
    rose500: '#F43F5E',
    orange500: '#F97316',

    // neutrals
    ink: '#0F0E1A',
    text: '#1F1B3A',
    muted: '#6B6985',
    soft: '#9D9BB5',
    line: '#E8E6F2',
    bg: '#FAF9FE',
    card: '#FFFFFF',
    cardSoft: '#F5F3FB',
  },
  // verse-card color palette (user-pickable)
  cardColors: [
    { id: 'indigo',   bg: 'linear-gradient(135deg, #6366F1, #8B5CF6)', solid: '#6366F1', tint: '#EEF2FF', label: 'Indigo' },
    { id: 'violet',   bg: 'linear-gradient(135deg, #8B5CF6, #A855F7)', solid: '#8B5CF6', tint: '#F3E8FF', label: 'Violeta' },
    { id: 'rose',     bg: 'linear-gradient(135deg, #F472B6, #EC4899)', solid: '#EC4899', tint: '#FCE7F3', label: 'Rosa' },
    { id: 'amber',    bg: 'linear-gradient(135deg, #FBBF24, #F97316)', solid: '#F59E0B', tint: '#FEF3C7', label: 'Ámbar' },
    { id: 'emerald',  bg: 'linear-gradient(135deg, #34D399, #14B8A6)', solid: '#10B981', tint: '#D1FAE5', label: 'Esmeralda' },
    { id: 'sky',      bg: 'linear-gradient(135deg, #38BDF8, #6366F1)', solid: '#0EA5E9', tint: '#E0F2FE', label: 'Cielo' },
    { id: 'crimson',  bg: 'linear-gradient(135deg, #FB923C, #EF4444)', solid: '#EF4444', tint: '#FEE2E2', label: 'Carmesí' },
    { id: 'midnight', bg: 'linear-gradient(135deg, #312E81, #1E1B4B)', solid: '#312E81', tint: '#E0E7FF', label: 'Medianoche' },
  ],
  // collection tag colors
  collectionColors: {
    Romanos:     { bg: '#FCE7F3', fg: '#BE185D', dot: '#EC4899' },
    Salmos:      { bg: '#E0F2FE', fg: '#0369A1', dot: '#0EA5E9' },
    Evangelios:  { bg: '#FEF3C7', fg: '#B45309', dot: '#F59E0B' },
    Promesas:    { bg: '#D1FAE5', fg: '#047857', dot: '#10B981' },
    Mañana:      { bg: '#EDE9FE', fg: '#6D28D9', dot: '#8B5CF6' },
    Memorizados: { bg: '#E0E7FF', fg: '#3730A3', dot: '#6366F1' },
    Favoritos:   { bg: '#FEE2E2', fg: '#B91C1C', dot: '#EF4444' },
    Proverbios:  { bg: '#CFFAFE', fg: '#0E7490', dot: '#06B6D4' },
  },
  // spacing
  s: { 1: 4, 2: 8, 3: 12, 4: 16, 5: 20, 6: 24, 7: 32, 8: 40, 9: 56, 10: 72 },
  // radius
  r: { sm: 8, md: 12, lg: 16, xl: 20, '2xl': 24, '3xl': 32, full: 9999 },
  // type
  font: {
    sans: '"Inter", -apple-system, BlinkMacSystemFont, system-ui, sans-serif',
    display: '"Plus Jakarta Sans", "Inter", system-ui, sans-serif',
    serif: '"Lora", "Iowan Old Style", Georgia, serif',
    mono: '"JetBrains Mono", ui-monospace, monospace',
  },
  shadow: {
    xs: '0 1px 2px rgba(15,14,26,0.04)',
    sm: '0 2px 8px rgba(79,70,229,0.06), 0 1px 2px rgba(15,14,26,0.04)',
    md: '0 8px 24px rgba(79,70,229,0.08), 0 2px 6px rgba(15,14,26,0.04)',
    lg: '0 18px 40px rgba(79,70,229,0.14), 0 6px 14px rgba(15,14,26,0.06)',
    xl: '0 32px 60px rgba(79,70,229,0.22), 0 10px 24px rgba(15,14,26,0.08)',
    glow: '0 0 0 4px rgba(139,92,246,0.18)',
  },
};

// Utility — translates strings (small i18n)
const T = {
  es: {
    appName: 'VersoRefuerzo',
    tagline: 'Memoriza. Practica. Vive la Palabra.',
    continueGoogle: 'Continuar con Google',
    continueApple: 'Continuar con Apple',
    privacy: '100% privado. Tus versos solo los ves tú.',
    home: 'Inicio',
    practice: 'Practicar',
    library: 'Biblioteca',
    profile: 'Perfil',
    addVerse: 'Agregar verso',
    yourCollections: 'Tus colecciones',
    todayStreak: 'Racha de hoy',
    days: 'días',
    versesLearning: 'aprendiendo',
    versesMastered: 'memorizados',
    practiceNow: 'Practicar ahora',
    dueToday: 'Para hoy',
    newVerse: 'Nuevo verso',
    reference: 'Referencia',
    version: 'Versión',
    icon: 'Ícono',
    color: 'Color',
    hint: 'Pista (opcional)',
    hintPlaceholder: 'p.ej. "camino, verdad, vida"',
    collections: 'Colecciones',
    save: 'Guardar verso',
    cancel: 'Cancelar',
    showHint: 'Necesito una pista',
    revealVerse: 'Revelar verso',
    iKnewIt: 'Lo recordé',
    sortOf: 'Más o menos',
    forgot: 'No lo recordé',
    again: 'Otra vez',
    hard: 'Difícil',
    good: 'Bien',
    easy: 'Fácil',
    seeAgainIn: 'Verás de nuevo en',
    minutes: 'min',
    hours: 'h',
    classicMode: 'Flashcards clásico',
    classicDesc: 'Repetición espaciada basada en ciencia',
    wordScramble: 'Palabras revueltas',
    scrambleDesc: 'Ordena las palabras del verso',
    verseMatch: 'Empareja versos',
    matchDesc: 'Conecta referencia con verso',
    fillTheGap: 'Completa el verso',
    gapDesc: 'Llena las palabras clave',
    streakChallenge: 'Reto del día',
    streakDesc: 'Un verso al día, mantén tu racha',
  },
  en: {
    appName: 'VersoRefuerzo',
    tagline: 'Memorize. Practice. Live the Word.',
    continueGoogle: 'Continue with Google',
    continueApple: 'Continue with Apple',
    privacy: '100% private. Only you see your verses.',
    home: 'Home',
    practice: 'Practice',
    library: 'Library',
    profile: 'Profile',
    addVerse: 'Add verse',
    yourCollections: 'Your collections',
    todayStreak: "Today's streak",
    days: 'days',
    versesLearning: 'learning',
    versesMastered: 'mastered',
    practiceNow: 'Practice now',
    dueToday: 'Due today',
    newVerse: 'New verse',
    reference: 'Reference',
    version: 'Version',
    icon: 'Icon',
    color: 'Color',
    hint: 'Hint (optional)',
    hintPlaceholder: 'e.g. "way, truth, life"',
    collections: 'Collections',
    save: 'Save verse',
    cancel: 'Cancel',
    showHint: 'I need a hint',
    revealVerse: 'Reveal verse',
    iKnewIt: 'I remembered',
    sortOf: 'Sort of',
    forgot: "Didn't remember",
    again: 'Again',
    hard: 'Hard',
    good: 'Good',
    easy: 'Easy',
    seeAgainIn: 'See again in',
    minutes: 'min',
    hours: 'h',
    classicMode: 'Classic flashcards',
    classicDesc: 'Science-based spaced repetition',
    wordScramble: 'Word scramble',
    scrambleDesc: 'Drag words into order',
    verseMatch: 'Verse match',
    matchDesc: 'Match reference to verse',
    fillTheGap: 'Fill the gap',
    gapDesc: 'Complete the key words',
    streakChallenge: 'Daily challenge',
    streakDesc: 'One verse a day, keep your streak',
  },
};

window.VR = VR;
window.T = T;
